title: "Kyle Laker"
url: "https://kylelaker.com"
email: "contact@laker.email"
author: Kyle Laker
logo: assets/image/site-logo.png
nav_logo: false
theme_color: "#f8f9fa"
# timezone: America/New_York

twitter:
  # username: kyle_laker
  card: summary
github: kylelaker
linkedin: kyle-laker-0339b346

bootstrap:
  version: "5.2.0-beta1"
  css_hash: "sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
  js_hash: "sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"

paginate: 5

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      disable: true

include:
  - "kylelaker.asc"
exclude:
  - "cdk"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
