title: "Kyle Laker"
url: "https://kylelaker.com"
email: "contact@laker.email"
author: Kyle Laker
logo: assets/image/site-logo.png
nav_logo: false
theme_color: "#f8f9fa"
# timezone: America/New_York

twitter:
  # username: kyle_laker
  card: summary
github: kylelaker
linkedin: kyle-laker-0339b346

bootstrap:
  version: "5.2.3"
  css_hash: "sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
  js_hash: "sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"

paginate: 5

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      disable: true

include:
  - "kylelaker.asc"
exclude:
  - "cdk"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-tsc
